apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app-container
        image: samkedge/go-app
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /health
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15      # how often to health check the pod
          timeoutSeconds: 5
        readinessProbe:          # To check if the Pod is ready to serve traffic or not
          httpGet:
            path: /ready
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1   

---

apiVersion: v1
kind: Service                      # Type of kubernetes resource
metadata:
    name: my-go-service            # Name of the resource
spec:
    type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
    ports:                         # Take incoming HTTP requests on port 8080 and forward them to the targetPort of 9090
    - name: http
      port: 8080
      targetPort: 9090
    selector:
        app: go-app                # Map any pod with label `app=go-app` to this service
