apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-go-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: {{ .Values.service.name }}
  selector:
{{ include "my-go-app.selectorLabels" . | indent 4 }}
